"""empty message

Revision ID: ff45ccecb921
Revises: 
Create Date: 2018-07-24 16:13:32.127527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff45ccecb921'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_2', table_name='b')
    op.drop_table('b')
    op.drop_table('a')
    op.add_column('user', sa.Column('confirm', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=32), nullable=True))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    op.drop_column('user', 'confirm')
    op.create_table('a',
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('sex', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('b',
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name_2', 'b', ['name'], unique=True)
    # ### end Alembic commands ###
